# Generated by Django 4.2.2 on 2023-06-18 15:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_category_options_category_friendly_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='image_preview',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='image'),
        ),
    ]
