# Generated by Django 4.2.2 on 2023-06-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_remove_resources_public_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='public_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
