# Generated by Django 4.2.2 on 2023-06-18 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0005_resources_public_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
