# Generated by Django 4.2.2 on 2023-06-19 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_alter_resources_submitted_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resources',
            old_name='submitted_by',
            new_name='user',
        ),
    ]
