# Generated by Django 4.2.2 on 2023-06-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_rename_submitted_by_resources_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
